// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista os clientes cadastrados (raz\xE3o social, CNPJ/CPF, contatos).",
  inputSchema: {
    search: z.string().optional().describe("Filtro por nome, raz\xE3o social ou CNPJ."),
    limit: z.number().int().positive().max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("clients").select("id, code, name, company_name, fantasy_name, cnpj, cpf, email, phone, city, state, client_type").order("name").limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`name.ilike.${s},company_name.ilike.${s},fantasy_name.ilike.${s},cnpj.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-plans.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_plans_default = defineTool2({
  name: "list_plans",
  title: "Listar planos",
  description: "Lista os planos dispon\xEDveis com nome, valor e descri\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("plans").select("*").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-client-plans.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_client_plans_default = defineTool3({
  name: "list_client_plans",
  title: "Listar planos de clientes",
  description: "Lista os v\xEDnculos de planos com clientes (contratos ativos e inativos).",
  inputSchema: {
    client_id: z2.string().uuid().optional(),
    only_active: z2.boolean().optional().describe("Apenas contratos ativos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("client_plans").select(
      "id, client_id, plan_id, value, payment_date, payment_method, start_date, end_date, is_active, clients(name, company_name), plans(name)"
    ).order("created_at", { ascending: false });
    if (client_id) q = q.eq("client_id", client_id);
    if (only_active) q = q.eq("is_active", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { client_plans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-financial-records.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_financial_records_default = defineTool4({
  name: "list_financial_records",
  title: "Listar registros financeiros",
  description: "Lista os registros financeiros (mensalidades) com filtros por status, cliente e intervalo de vencimento.",
  inputSchema: {
    status: z3.enum(["pendente", "quitado", "atrasado"]).optional().describe("Filtrar por status."),
    client_id: z3.string().uuid().optional().describe("ID do cliente."),
    due_from: z3.string().optional().describe("Data m\xEDnima de vencimento (YYYY-MM-DD)."),
    due_to: z3.string().optional().describe("Data m\xE1xima de vencimento (YYYY-MM-DD)."),
    limit: z3.number().int().positive().max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, client_id, due_from, due_to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("financial_records").select(
      "id, client_id, plan_id, client_plan_id, value, original_value, due_date, payment_date, payment_method, status, observations, clients(name, company_name)"
    ).order("due_date", { ascending: false }).limit(limit ?? 100);
    if (status) q = q.eq("status", status);
    if (client_id) q = q.eq("client_id", client_id);
    if (due_from) q = q.gte("due_date", due_from);
    if (due_to) q = q.lte("due_date", due_to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { records: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.52.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Resumo financeiro",
  description: "Retorna totais de recebido, pendente e atrasado. Pode filtrar por intervalo de vencimento.",
  inputSchema: {
    due_from: z4.string().optional().describe("Data m\xEDnima de vencimento (YYYY-MM-DD)."),
    due_to: z4.string().optional().describe("Data m\xE1xima de vencimento (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ due_from, due_to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    let q = sb.from("financial_records").select("value, status, due_date");
    if (due_from) q = q.gte("due_date", due_from);
    if (due_to) q = q.lte("due_date", due_to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    let paid = 0, pending = 0, overdue = 0;
    for (const r of data ?? []) {
      const v = Number(r.value) || 0;
      if (r.status === "quitado") paid += v;
      else if (r.status === "atrasado") overdue += v;
      else if (r.status === "pendente") {
        if (r.due_date < today) overdue += v;
        else pending += v;
      }
    }
    const summary = {
      paid,
      pending,
      overdue,
      total: paid + pending + overdue,
      count: data?.length ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iqxorxuhupbfgbrbsguj";
var mcp_default = defineMcp({
  name: "gerenciador-online-mcp",
  title: "Gerenciador Online MCP",
  version: "0.1.0",
  instructions: "Ferramentas para consultar clientes, planos, contratos e situa\xE7\xE3o financeira do Gerenciador Online. Use list_clients para buscar clientes, list_plans e list_client_plans para planos e contratos, e list_financial_records/financial_summary para dados financeiros.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    list_plans_default,
    list_client_plans_default,
    list_financial_records_default,
    financial_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
